pipelines:
  udp_to_file:
    settings:
      decoder: raw
#      decoder: json
    input:
      type: socket
      network: udp
      address: ':514'
    actions:
#      - type: debug
#        interval: 1s
#        first: 10
#        thereafter: 5
      - type: parse_re2
        field: message
        re2: '^<(?P<priority>\d+)>(?P<syslog_time>\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2})\s+(?P<host>\S+)\s+(?P<service>\S+):\s*(?P<remote_addr>[^|]*)\|(?P<remote_user>[^|]*)\|\[(?P<timestamp>[^\]]+)\]\|(?P<request>[^|]*)\|(?P<resp_code>[^|]*)\|(?P<body_bytes_sent>[^|]*)\|(?P<http_referer>[^|]*)\|(?P<useragent>[^|]*)\|(?P<duration>[^|]*)\|(?P<request_body>[^|]*)$'

#      - type: debug
#        interval: 1s
#        first: 10
#        thereafter: 5
      - type: convert_utf8_bytes
        fields:
          - request_body
      - type: convert_date
        source_formats:
          - rfc3339
        target_format: unixtime
      - type: modify
        request_type: ${request|re("^(GET|POST|PUT|DELETE|OPTIONS)\\s+(\\/[^?]+)(\\?[^\\s]+)?\\s+HTTP\\/\\d+\\.\\d+$",-1,[1],",",true)}
      - type: modify
        path: ${request|re("^(GET|POST|PUT|DELETE|OPTIONS)\\s+(\\/[^?]+)(\\?[^\\s]+)?\\s+HTTP\\/\\d+\\.\\d+$",-1,[2],",",true)}
      - type: modify
        params: ${request|re("^(GET|POST|PUT|DELETE|OPTIONS)\\s+(\\/[^?]+)(\\?[^\\s]+)?\\s+HTTP\\/\\d+\\.\\d+$",-1,[3],",",true)}
#      - type: debug
#        interval: 1s
#        first: 10
#        thereafter: 5
    output:
      type: clickhouse
      addresses:
        - clickhouse-01
      database: default
      table: logs_table_v2
      user: default
      password: '12345'
      columns:
        - name: timestamp
          type: DateTime
        - name: host
          type: String
        - name: duration
          type: Float32
        - name: request_type
          type: String
        - name: remote_addr
          type: String
        - name: path
          type: String
        - name: params
          type: String
        - name: resp_code
          type: UInt32
        - name: useragent
          type: String
        - name: request_body
          type: String
