#version: '2'

services:
  chi_app:
    build: app
    restart: always
    networks:
      - logging

  clickhouse-01:
    container_name: clickhouse-01
    user: "502:20"
    image: clickhouse:24.3.14.35
    restart: always
    logging:
      options:
        max-size: "10M"
        max-file: "10"
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/ch_db_1:/var/lib/clickhouse
      - ./clickhouse/user_files:/var/lib/clickhouse/user_files
      - ./clickhouse/logs/log_1:/var/log
      - ./clickhouse/configs/config_1.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/configs/users_1.xml:/etc/clickhouse-server/users.xml
    networks:
      - logging
  file_d:
    image: ghcr.io/ozontech/file.d:v0.58.1-alpine
    restart: always
    container_name: file_d
    depends_on:
      - clickhouse-01
    ports:
      - "514:514"
    command:
      - '/file.d/file.d'
      - '--config'
      - 'config.yaml'
    volumes:
      - ./file.d/config/config.yaml:/file.d/config.yaml
    networks:
      - logging
  nginx:
    #    build: ./nginx-syslog
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - file_d
      - chi_app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - logging

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/
      - ./grafana/data:/var/lib/grafana/
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: "grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource,grafana-clickhouse-datasource"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    networks:
      - logging


networks:
  logging: